# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: NASA GES DISC
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyter-notebook-from-json-extension
project_short_description: An extension from preloading JupyterLite notebooks into
    a users browser
python_name: jupyter_notebook_from_json_extension
repository: https://github.com/gesdisc/jupyter-notebook-from-json-extension
test: false

